sonar.projectKey=Thamysis_sistema-controle-estoque
sonar.organization=thamysis
sonar.sources=.
sonar.exclusions=static/css/bootstrap*.css,static/js/*.min.js,**/__pycache__/**,.github/**
sonar.python.version=3.11

sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=tests/**,static/**,templates/**